### ISSUE TITLE
build constraints exclude all Go files

### ISSUE THREAD

**Issue by chenxilol** [AndreyGermanov/yolov8_onnx_go#3]
I came across github.com/yalue/onnxruntime_go when compiling: build constraints exclude all Go files in D:envgopkgmodgithub.comyalueonnxruntime_go@v1.9.0。

**Comment by AndreyGermanov** [comment]
Clean package cache of this project and update packages:

Remove go.sum file
Exec the following commands:

```
go mod download github.com/yalue/onnxruntime_go
go mod download github.com/nfnt/resize
```

Then try again.

**Comment by Cello2115** [comment]
still like this problem when i clean the cache,delete go.sum and exec the follow command

**Comment by AndreyGermanov** [comment]
Which operating system version and Go version do you use?

**Comment by AndreyGermanov** [comment]
> still like this problem when i clean the cache,delete go.sum and exec the follow command

Which operating system version and Go version do you use?

**Comment by Cello2115** [comment]
win11 and go1.12.6

**Comment by AndreyGermanov** [comment]
The Go version should be at least 1.18, recommend upgrading to the latest one.

If you experienced this problem on Windows, try the following.

1. Check if GCC (GNU C Compiler) installed in your system by running:

```bash
gcc --version
```

If it's not installed, download it from here: http://www.equation.com/servlet/equation.cmd?fa=fortran, install and reboot the system.

2. Enable CGO, by running the following command:

```bash
go env -w CGO_ENABLED=1
```

3. Run the app as usual

```bash
go run .
```

**Comment by Cello2115** [comment]
thanks! it's runs normally
